### PR TITLE
Incorporate input field validations

### LINKED ISSUE #3: add true field validations
prevent the TRM score from being displayed if any of the fields are outside of their validation ranges where applicable.

### PR DESCRIPTION
**Pull request by vsriram24**
Use the package "shinyvalidate" to include input checks before TRM calculation.

### CODE REVIEW

**Comment by vsriram24** [comment]
@monicagerber another feature ready for review - FYI as of now, the checks only verify that input values are > 0 (and for the percentage field, between 0 and 100). For future iterations, we may want to include domain knowledge to suggest reasonable ranges for each field.

**Review by monicagerber — COMMENTED** [review]
Will review when previous PR is merged and any conflicts are resolved. let me know when it's ready.

**Comment by vsriram24** [comment]
@monicagerber merge conflicts should be resolved here now

**Review by monicagerber — APPROVED** [review]
Looks great!

**Pull request merged**
